name: bf545
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - black
  - mothur=1.43.0
  - pandoc=2.9.2
  - python=3.6.7
  - r-base=3.6.2
  - r-broom
  - r-caret=6.0
  - r-here
  - r-rcolorbrewer
  - r-rmarkdown=2.1
  - r-styler
  - r-tidyverse=1.3.0
  - r-usethis=1.5.1
  - r-vegan=2.5
  - snakemake=5.3.0
  - sra-tools=2.10.3
  - fastqc=0.11.9
  - trimmomatic=0.39
  - metaphlan2=2.96.1
