name: bf545
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - black
  - pandoc=2.9.2
  - python=3.6.7
  - r-base=3.6.2
  - r-broom
  - r-here
  - r-rcolorbrewer
  - r-rmarkdown=2.1
  - r-styler
  - r-tidyverse=1.3.0
  - r-usethis=1.5.1
  - snakemake=5.3.0