name: build

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  render:
    name: build
    runs-on: macOS-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: actions/setup-python@v1
      - name: Configure git
        run: |
          git config --local user.email "noreply@github.com"
          git config --local user.name "GitHub"
      - name: Style R code
        run: |
          R -e "install.packages(c('usethis', 'styler'))"
          git status
          Rscript -e 'usethis::use_tidy_style()'
          git add .
          git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m '🎨 Style R code' || echo "Nothing to commit"
      - name: Style Python code
        shell: bash -l {0}
        run: |
          pip install black
          black .
          git add .
          git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m '🎨 Style Python code 🐍' || echo "Nothing to commit"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
